tasks:
  - init: |
      curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJf - --strip-components=1 -C /home/gitpod/.local/bin typst
      sudo apt-get update && sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra

vscode:
  extensions:
    - myriad-dreamin.tinymist
