tasks:
  - init: |
      curl -L --create-dirs https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJf - --strip-components=1 -C /home/gitpod/.local/bin
      curl -L --create-dirs https://github.com/adobe-fonts/source-han-super-otc/releases/latest/download/NotoCJK.ttc -o ~/.local/fonts/NotoCJK.ttc
      fc-cache -fv

vscode:
  extensions:
    - myriad-dreamin.tinymist
